name: quran
description: Quran text, translation, audio URLs, and details of pages, juz, surah, ayah, place of revelation etc.
version: 1.2.2
homepage: https://github.com/aqeelshamz/quran

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  dartarabic: ^0.3.1  # حاول تحديث النسخة لو متوفرة

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  # لو عندك أصول أو خطوط تضيفها هنا
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
